Repository socketsupply/socket, pull requests merged in 2023-02, with the labels that each got.

#75 android: Resolve windows build issues
  .gitignore
  bin/install.ps1
  src/cli/cli.cc
Labels: windows, android, cli, needs qa

#153 refactor(test): rewrite test runners in js
  test/package.json
  test/scripts/bootstrap-android-emulator.sh
  test/scripts/poll-adb-logcat.sh
  test/scripts/test-android-emulator.sh
  test/scripts/test-android.js
  test/scripts/test-android.sh
  test/scripts/test-desktop.js
  test/scripts/test-desktop.sh
  test/scripts/test-ios-simulator.js
  test/scripts/test-ios-simulator.sh
Labels: tests

#167 linux: free resources created by gtk
  src/ipc/bridge.cc
  src/window/linux.cc
Labels: bug, linux

#179 Use mutex lock for std{out,err} callbacks
  src/process/process.hh
  src/process/unix.cc
  src/process/win.cc
Labels: bug

#181 fix(test/src/dns.js): drop cloudflare.com
  test/src/dns.js
Labels: tests

#185 Fix module import path URI for iOS
  src/ipc/bridge.cc
Labels: bug

#206 Fix 'Window::getScreenSize()' on Linux
  src/window/linux.cc
Labels: bug, linux
