Repository socketsupply/socket, pull requests merged in 2023-11, with the labels that each got.

#745 fix: use a `shared_ptr` for IPC HTTP request cancellation callback
  src/extension/ipc.cc
  src/ipc/bridge.cc
  src/ipc/ipc.cc
  src/ipc/ipc.hh
Labels: enhancement, runtime

#748 fix(src/ipc/bridge.cc): fix 'HOME' for user on windows in mounts
  src/ipc/bridge.cc
Labels: bug, windows, runtime

#750 refactor(api/notifications): fix 'Notification.requestPermission'
  api/index.d.ts
  api/notification.js
Labels: javascript, api

#747 Introduce '[build] build.forward_arguments'
  api/CONFIG.md
  src/cli/cli.cc
  src/cli/templates.hh
Labels: cli, config

#757 Fix iOS container path resolution
  src/core/types.hh
  src/ipc/bridge.cc
Labels: bug, ios

#761 feat(api/path): introduce well known path constants
  api/index.d.ts
  api/path.js
  api/path/index.js
  api/path/well-known.js
  src/android/bridge.kt
  src/ipc/bridge.cc
Labels: enhancement, javascript, api, runtime

#760 feat(api/mime): introduce MIME database
  api/index.d.ts
  api/mime.js
  api/mime/application.json
  api/mime/audio.json
  api/mime/font.json
  api/mime/image.json
  api/mime/index.js
  api/mime/model.json
  api/mime/multipart.json
  api/mime/text.json
  api/mime/video.json
  test/src/mime.js
Labels: enhancement, javascript, api

#763 Fix os.platform bug
  api/internal/permissions.js
Labels: bug

#778 improve api defaults, property check peer when offline
  api/index.d.ts
  api/stream-relay/index.js
  api/stream-relay/packets.js
  api/stream-relay/sugar.js
Labels: javascript, api

#788 refactor(src/core/javascript.cc): 'dragdropfiles'
  src/core/javascript.cc
Labels: enhancement, runtime

#796 fix(src/cli/cli.cc): '_' needs to be '_1' for android JNI package name
  src/cli/cli.cc
Labels: bug, android, cli, build

#802 fix(src/cli/cli.cc): fix headless mode
  src/cli/cli.cc
Labels: cli, config

#803 chore(test/src/application.js): increase timeout for backend.open({ force: true })) to send event
  test/src/application.js
Labels: tests

#814 fix(src/ipc/bridge.cc): escape mount mapping keys
  src/ipc/bridge.cc
Labels: bug, runtime

#815 Release v0.5.1
  VERSION.txt
  api/README.md
  clib.json
  npm/packages/@socketsupply/socket-darwin-arm64/package.json
  npm/packages/@socketsupply/socket-darwin-x64/package.json
  npm/packages/@socketsupply/socket-linux-arm64/package.json
  npm/packages/@socketsupply/socket-linux-x64/package.json
  npm/packages/@socketsupply/socket-win32-x64/package.json
  npm/packages/@socketsupply/socket/package.json
Labels: release
