Repository socketsupply/socket, pull requests merged in 2023-09, with the labels that each got.

#546 fix(src/common.hh): set type in 'msleep' prototype
  src/common.hh
Labels: bug

#551 Fix typescript typings
  api/README.md
  api/crypto.js
  api/dgram.js
  api/diagnostics/channels.js
  api/diagnostics/metric.js
  api/dns/index.js
  api/errors.js
  api/events.js
  api/extension.js
  api/fs/binding.js
  api/fs/handle.js
  api/fs/index.js
  api/fs/promises.js
  api/hooks.js
  api/index.d.ts
  api/module.js
  api/path/index.js
  api/path/posix.js
  api/path/win32.js
  api/peer.js
  test/src/dns.js
Labels: api, typescript

#560 Fix adding double '.js' extension
  src/ipc/bridge.cc
  src/window/win.cc
Labels: bug

#566 Fix mobile builds
  src/cli/cli.cc
  src/common.hh
  src/desktop/main.cc
  src/init.cc
Labels: bug

#561 Release v0.4.0
  VERSION.txt
  api/README.md
  clib.json
  npm/packages/@socketsupply/socket-darwin-arm64/package.json
  npm/packages/@socketsupply/socket-darwin-x64/package.json
  npm/packages/@socketsupply/socket-linux-arm64/package.json
  npm/packages/@socketsupply/socket-linux-x64/package.json
  npm/packages/@socketsupply/socket-win32-x64/package.json
  npm/packages/@socketsupply/socket/package.json
Labels: release

#579 fix(determine_cxx): ignore clang binaries that don't have `--version`
  bin/functions.sh
Labels: bug, build

#587 import 'socket:internal/init' when interactive
  src/core/runtime-preload.hh
Labels: enhancement

#588 Handle various common mime types on Windows
  src/window/win.cc
Labels: bug, windows

#592 fix(src/cli/templates.hh): fix default '[webview]' config
  api/config.md
  src/cli/templates.hh
Labels: bug, cli, config

#593 refactor(src/cli/cli.cc): allow async build after script
  src/cli/cli.cc
Labels: enhancement, cli

#591 chore(src/cli/cli.cc): only remove 'socket/node_modules'
  src/cli/cli.cc
Labels: bug, cli

#590 Allow configuration of android icon and resources
  src/cli/cli.cc
  test/socket.ini
  test/src/icon.png
Labels: android, cli

#603 chore(CONTRIBUTING.md): update links and cleanup
  CONTRIBUTING.md
Labels: documentation

#613 feat(src/cli/cli.cc): add --name option to ssc init
  src/cli/cli.cc
  src/cli/templates.hh
Labels: cli

#614 fix(api/url): fix missing static 'URL' properties
  api/url/index.js
Labels: api
